# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make forecast models

#on:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron: "40 * * * *"
on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Update data with current hourly report"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r forecast-requirements.txt
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Toronto
      - name: Get data
        env:
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
        run: |
          python scripts/getdata.py
      - name: Make forecast
        env:
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
        run: |
          python scripts/make-forecast.py
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           push_options: '--force'
#           skip_fetch: false
